spring:
  thymeleaf:
    cache: false

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource

    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
      url: jdbc:mysql://localhost:3306/loans?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      # druid 配置
      initial-size: 5
      max-active: 50
      min-idle: 3
      #      配置监控统计拦截器 日志配置  Slf4j  logback
      #      stat 监控数据库性能
      #      wall  用于防火墙
      #      日志先关 slf4j  logback  log4j  log4j2
      filter: stat,wall,slf4j
      web-stat-filter:
        enabled: true
        log-slow-sql: true
        url-pattern:  /*
        # 排除不拦截的 请求
        exclusions: "*.js,*.png,/druid/*"
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #  是否可以使用重置功能
        reset-enable: true
        login-username: admin
        login-password: admin
        #  允许访问的id
        allow: 127.0.0.1
        #  和名单
        deny: ""
#  mybatis整合

mybatis:
  # 别名
  type-aliases-package:  com.vip.loans.domain.entity
  configuration:
    map-underscore-to-camel-case: true


mybatis-plus:
  mapper-locations: classpath:mappers/**/*.xml
  global-config:
    db-config:
      id-type: auto

logging:
  level:
    com.vip.demo.mapper: debug


server:
  servlet:
    context-path: /api
